api_url: https://api.proxyapi.ru/openai/v1/ # URL доступа к API. Замените на https://api.openai.com/v1/ для доступа напрямую к OpenAI
api_key: [YOUR-API-KEY]
telegram_bot_token: [YOUR-TELEGRAM-BOT-TOKEN]
files_path: upload # Путь к директории с файлами
name: [YOUR-ASSISTANT-NAME] # Название ассистента
instructions: [YOUR-ASSISTANT-INSTRUCTIONS] # Инструкции для ассистента
model: gpt-4-turbo # Модель для ассистента
tools:
  - file_search
max_context_messages: 10  # Максимальное количество сообщений в контексте
