api_url: https://api.proxyapi.ru/openai/v1/
api_key: [YOUR-API-KEY]
telegram_bot_token: [YOUR-TELEGRAM-BOT-TOKEN]
files_path: upload
name: [YOUR-ASSISTANT-NAME]
instructions: [YOUR-ASSISTANT-INSTRUCTIONS]
model: gpt-4-turbo
tools:
  - file_search
